# Generated by Django 4.2.7 on 2023-11-24 00:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('account', '0002_alter_user_managers_user_date_joined_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('form', models.FloatField(choices=[('GRAM', 'Gram'), ('PILLS', 'Pills'), ('DROPS', 'Drops'), ('CAPSULE', 'Capsule'), ('MILIGRAM', 'Miligram')], help_text='what form is the medicine?')),
                ('quantity', models.FloatField(help_text='Choose the medication strength')),
                ('interval', models.TextField(choices=[('DAILY', 'Daily'), ('CYCLIC', 'Cyclic'), ('WEEKLY', 'Weekly'), ('INTERVAL', 'Interval'), ('SPECIFIC', 'Specific')], help_text='How do you take this medication?')),
                ('start_date', models.DateTimeField(help_text='Set treatment duration')),
                ('end_date', models.DateTimeField(blank=True, help_text='Calculate end date from input (How long are you taking the medicine?)', null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.drug')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pill_count', models.IntegerField(blank=True, help_text='Number of pill(s)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('dosage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='tracker.dosage')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intruction', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.patient')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='DosageUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(help_text='Time and date taken')),
                ('status', models.TextField(choices=[('TAKEN', 'Taken'), ('PENDING', 'PENDING'), ('OVERDUE', 'Overdue')])),
                ('dosage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.dosage')),
            ],
        ),
        migrations.AddField(
            model_name='dosage',
            name='prescription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.prescription'),
        ),
    ]
